apiVersion: v1 # the app version
kind: Service #define the object we want to build
metadata:
  name: nginx-app-loadbalancer # name we want to call the service with
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # backend port